### ISSUE TITLE
Password doesn't match! (During registration)

### ISSUE THREAD

**Issue by shouseworth** [abdulhasibuddin/PHP-Secure-Registration-Login-System-v1--with-Email-Verification#1]
I keep getting message "Password doesn't match!" when I hit submit.  Tried several times.

**Comment by abdulhasibuddin** [comment]
Sorry, but cannot find any error when registering. Please, delete your files (you downloaded from here),  re-download files, and if you get any error again, please give a snapshot.
My registration codes are running here:
https://myregistrationwebsite.000webhostapp.com/registrationPage.php

**Comment by shouseworth** [comment]
Thank you for the prompt response!  Will let you know.

**Comment by abdulhasibuddin** [comment]
Thank you, but there are some problems for showing error messages when the password characters are invalid, this issue is resolved here:
https://github.com/abdulhasibuddin/PHP-Secure-Registration-Login-System
So, please try this, and let me know!

**Comment by shouseworth** [comment]
Trying to use password Abcd1234!

Same error as when done on Mac

**Comment by shouseworth** [comment]
I’m blind....cannot use “!” character.   Is there a way to add requirement for special characters and add them?

Thank you.

**Comment by abdulhasibuddin** [comment]
Yes, edit the regular expression in "passwordValidation.php" file, but you also would need to edit each regular expression where ever there is a "Password" or "Confirm Password" field, e.g. in "loginPage2.php"!

**Comment by shouseworth** [comment]
Thank you.

**Comment by shouseworth** [comment]
I have tried to add the “!” unsuccessfully. What would that look line/section of code look like?  I know where all it needs to be modified.

 

Thank you again for all of your assistance.

**Comment by abdulhasibuddin** [comment]
if (!preg_match('/^[a-zA-Z0-9_!]*$/', $password)){...}
just add the characters you want to permit, or use Perl-like Regex.

**Comment by shouseworth** [comment]
Thank you for your assistance.
